using System;
using System.Threading;

namespace HelloWorld.cs
{
	public class HelloWorld
	{
		public static void Main(string[] args)
		{
			Console.WriteLine("______________________");
			Console.WriteLine("| ");
			Console.WriteLine("| ");
			Console.WriteLine("| ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                 * | ");
			Console.WriteLine("                   | ");
			Console.WriteLine(" ");
			Console.WriteLine(" ");
			Console.WriteLine(" ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine(" ");
			Console.WriteLine("| ");
			Console.WriteLine("| ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                  *| ");
			Console.WriteLine(" ");
			Console.WriteLine(" ");
			Console.WriteLine(" ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine(" ");
			Console.WriteLine(" ");
			Console.WriteLine("| ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                 *   ");
			Console.WriteLine(" ");
			Console.WriteLine(" ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine(" ");
			Console.WriteLine(" ");
			Console.WriteLine("                   | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("|                    ");
			Console.WriteLine("                *    ");
			Console.WriteLine(" ");
			Console.WriteLine(" ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine(" ");
			Console.WriteLine(" ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("               *     ");
			Console.WriteLine(" ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine(" ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("              *      ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("_____________*________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("                     ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|           *        ");
			Console.WriteLine("|_____________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|          *         ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("|         *        | ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("                     ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("                   | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("|        *         | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("|                    ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|       *          | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|      *             ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                     ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("                     ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|     *              ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("|                    ");
			Console.WriteLine("|    *               ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("|   *                ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("|                    ");
			Console.WriteLine("|  *                 ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("                     ");
			Console.WriteLine("|                    ");
			Console.WriteLine("| *                  ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("                     ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|*                 | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("| *                | ");
			Console.WriteLine("|                  | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|  *               | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                     ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|   *              | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("______________________");
			Thread.Sleep(500);
			Console.Clear();
			Console.WriteLine("______________________");
			Console.WriteLine("                     ");
			Console.WriteLine("                     ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("|                    ");
			Console.WriteLine("                     ");
			Console.WriteLine("     *             | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("                   | ");
			Console.WriteLine("___________________|__");
			Thread.Sleep(500);
			Console.Clear();


			Thread.Sleep(2000);
			Console.WriteLine("I Love Stephanie Quinn!");
			Thread.Sleep(2000);
			Console.Clear();
			
			
		}
	}
}
